[build-system]
requires      = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]

[project]
name            = "snake-corp-product-data"
version         = "1.0.0"
authors         = [{ name = "Viper", email = "viper@snake-corp.com" }]
description     = "Our products"
requires-python = ">=3.7"
keywords        = ["one", "two"]
license         = { text = "BSD-3-Clause" }
classifiers     = ["Programming Language :: Python :: 3"]
